CI: Fix errors

diff --git a/.github/workflows/make.yaml b/.github/workflows/make.yaml
--- a/.github/workflows/make.yaml
+++ b/.github/workflows/make.yaml
@@ -669,9 +669,9 @@ jobs:
         # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
         run:  |
           [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit "::warning::At least one regression in test suite"
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
           [ -n "$(grep -e "FAIL\s*0" ./test-suite-vm.log)" ] || echo "::warning::At least one test failed with VM"
-          [ -z "$(grep -e "REGRESSION" ./test-suite-vm.log)" ] || "::warning::At least one regression in test suite with VM"
+          [ -z "$(grep -e "REGRESSION" ./test-suite-vm.log)" ] || echo "::warning::At least one regression in test suite with VM"
           echo Finished analyzing test suite results.
 
       - name: test history file creation
@@ -947,16 +947,9 @@ jobs:
         # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
         run:  |
           [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit "::warning::At least one regression in test suite"
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite-vm.log)" ] || echo "::warning::At least one test failed with VM"
-          [ -z "$(grep -e "REGRESSION" ./test-suite-vm.log)" ] || "::warning::At least one regression in test suite with VM"
-          echo Finished analyzing test suite results.
-
-      - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
           [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite-vm.log)" ] || echo "::warning::At least one test failed with VM"
+          [ -z "$(grep -e "REGRESSION" ./test-suite-vm.log)" ] || echo "::warning::At least one regression in test suite with VM"
           echo Finished analyzing test suite results.
 
       - name: test history file creation
